image: openjdk:11

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == 'dev'

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


build:
  stage: build
  script:
    - ./gradlew
    
test:
  stage: test
  script:
    - ./gradlew verify
  artifacts:
    reports:
      junit:
        - build/test-results/**/TEST-*.xml

integration:
  stage: test
  trigger: 
    project: hca/ingest-integration-tests
    branch: dev
    strategy: depend

