services:
  - name: quay.io/ebi-ait/ingest-base-images:docker-dind
    alias: docker

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == 'dev'

variables:
  FASTQ_VALIDATOR_IMAGE: "quay.io/ebi-ait/fastq_utils:54bcf9f"
  APP_NAME: "ingest-core"
  DEV_REPLICAS: 1
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA

stages:
  - build
  - unit-test
  - deploy-dev
  - integration

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy-dev:
  stage: deploy-dev
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: dev
    url: https://dev.contribute.data.humancellatlas.org/
  script:
    - helm package k8s/$APP_NAME
    - helm upgrade -f k8s/dev.yaml $APP_NAME k8s/$APP_NAME --set-string environment=dev,image=$IMAGE_NAME,replicas=$DEV_REPLICAS --wait --install

unit-test:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: unit-test
  script:
    - ./gradlew verify
  artifacts:
    reports:
      junit:
        - build/test-results/**/TEST-*.xml

integration:
  stage: integration
  trigger: 
    project: hca/ingest-integration-tests
    branch: dev
    strategy: depend


