image: docker:stable
services:
  - docker:dind

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == 'dev'

stages:
  - build
  - unit-test
  - deploy-dev
  - integration

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


build:
  stage: build
  tags:
    - dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    
unit-test:
  image: openjdk:11
  stage: unit-test
  script:
    - ./gradlew verify
  artifacts:
    reports:
      junit:
        - build/test-results/**/TEST-*.xml

integration:
  stage: integration
  trigger: 
    project: hca/ingest-integration-tests
    branch: dev
    strategy: depend


