services:
  - name: quay.io/ebi-ait/ingest-base-images:docker-dind
    alias: docker

variables:
  APP_NAME: $CI_PROJECT_NAME
  DEV_REPLICAS: 1
  IMAGE_NAME: quay.io/ebi-ait/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - unit-test
  - deploy-dev
  - integration-dev
  - deploy-staging
  - integration-staging
  - deploy-prod
  - integration-prod

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

unit-test:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: unit-test
  script:
    - ./gradlew verify
  artifacts:
    reports:
      junit:
        - build/test-results/**/TEST-*.xml

deploy-dev:
  stage: deploy-dev
  only:
    - dev
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: dev
    url: https://dev.contribute.data.humancellatlas.org/
    kubernetes:
      namespace: dev-environment
  script:
    - helm package k8s/$APP_NAME
    - helm upgrade -f k8s/dev.yaml $APP_NAME k8s/$APP_NAME --set-string environment=dev,image=$IMAGE_NAME,replicas=$DEV_REPLICAS --wait --install

integration-dev:
  stage: integration-dev
  only:
    - dev
  trigger: 
    project: hca/ingest-integration-tests
    branch: dev
    strategy: depend

deploy-staging:
  stage: deploy-staging
  only:
    - master
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: staging
    url: https://staging.contribute.data.humancellatlas.org/
    kubernetes:
      namespace: staging-environment
  script:
    - helm package k8s/$APP_NAME
    - helm upgrade -f k8s/dev.yaml $APP_NAME k8s/$APP_NAME --set-string environment=staging,image=$IMAGE_NAME,replicas=$DEV_REPLICAS --wait --install

integration-staging:
  stage: integration-staging
  only:
    - master
  trigger:
    project: hca/ingest-integration-tests
    branch: staging
    strategy: depend

deploy-prod:
  stage: deploy-prod
  only:
    - master
  when: manual
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: prod
    url: https://contribute.data.humancellatlas.org/
    kubernetes:
      namespace: prod-environment
  script:
    - helm package k8s/$APP_NAME
    - helm upgrade -f k8s/dev.yaml $APP_NAME k8s/$APP_NAME --set-string environment=prod,image=$IMAGE_NAME,replicas=$DEV_REPLICAS --wait --install

integration-prod:
  stage: integration-prod
  only:
    - master
  trigger:
    project: hca/ingest-integration-tests
    branch: prod
    strategy: depend


