apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingestion
  name: ingest-core-service
  namespace: ingest-core-3022-{{ .Values.environment }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ingest-core
  sessionAffinity: None
  type: NodePort
