cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - echo "Performing build..."

stages:
  - build
  - test

build:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: build
  script:
    - ./gradlew build -x test --info --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar

test:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: test
  script:
    - ./gradlew test
  allow_failure: true
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

docker-build:
  stage: package
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .


