cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - echo "Performing build..."

stages:
  - build
  - test
  - package

build:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: build
  script:
    - ./gradlew build -x test --info --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar

test:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  stage: test
  script:
    - ./gradlew test
  allow_failure: true
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

docker-build:
  stage: package
  script:
    - docker build -t ingest-core-morphic:$CI_COMMIT_SHA .
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ingest-core-morphic:$CI_COMMIT_SHA
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ingest-core-morphic:$CI_COMMIT_SHA


