apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-core-deployment
  namespace: morphic-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-core
  template:
    metadata:
      labels:
        app: ingest-core
    spec:
      containers:
        - name: ingest-core-container
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_URI
              value: mongodb+srv://morphic-prod:morphicProd#12345@morphicprodcluster.gvr5bkw.mongodb.net/MorphicProd?retryWrites=true&w=majority
            - name: RABBIT_HOST
              value: rabbitmq-service
            - name: RABBIT_PORT
              value: "5672"
            - name: AWS_COGNITO_DOMAIN
              value: "https://morphic.auth.eu-west-2.amazoncognito.com/oauth2"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: eu-west-2  # Optionally specify AWS region as an environment variable
          imagePullPolicy: Always
