apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-core-deployment
  namespace: morphic-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-core
  template:
    metadata:
      labels:
        app: ingest-core
    spec:
      containers:
        - name: ingest-core-container
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ingest-core-secrets
                  key: SPRING_DATA_MONGODB_URI
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ingest-core-secrets
                  key: SPRING_DATA_MONGODB_URI
            - name: RABBIT_HOST
              value: rabbitmq-service
            - name: RABBIT_PORT
              value: "5672"
            - name: AWS_COGNITO_DOMAIN
              value: "https://morphic.auth.eu-west-2.amazoncognito.com/oauth2"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: eu-west-2  # Optionally specify AWS region as an environment variable
            - name: MORPHIC_PROVIDER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: morphic-globus-credentials
                  key: MORPHIC_PROVIDER_CLIENT_ID
            - name: MORPHIC_PROVIDER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: morphic-globus-credentials
                  key: MORPHIC_PROVIDER_CLIENT_SECRET
            - name: MORPHIC_EBI_COLLECTION_UUID
              value: "14a0be5f-226c-49fe-b65f-dba083d67fc3"
            - name: MORPHIC_DEST_ROOT
              value: "/ebi/ftp/private/morphic-transfer"
            - name: MORPHIC_UPLOAD_SUBDIR
              value: "submissions"
            - name: MORPHIC_GLOBUS_ACL_COLLECTION_ID
              valueFrom:
                secretKeyRef:
                  name: morphic-globus-credentials
                  key: MORPHIC_GLOBUS_ACL_COLLECTION_ID
          imagePullPolicy: Always
